services:
    web:
        build:
            context: ../
            dockerfile: docker/web/Dockerfile
        ports:
            - 3000:3000
    hc_api:
        build:
            context: ../
            dockerfile: docker/hc_api/Dockerfile
        ports:
            - 42069:42069
        depends_on:
            - db
    db:
        build:
            context: ../
            dockerfile: docker/db/Dockerfile
        restart: always
        ports:
            - 5432:5432
        shm_size: 128mb
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: hc
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
